language: go

go:
  - "1.11.x"

install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - go get golang.org/x/lint/golint
  - dep ensure -v

script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
  - dep status
  - go vet
  - go fmt
  - golint github.com/JosiahWitt/priv

after_success:
  - bash <(curl -s https://codecov.io/bash)
